# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    name:  Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name:  Get latest code
      uses: actions/checkout@v2
    - run: echo 'VUE_APP_DEFAULT_CONFIG_URL=${{ secrets.ENV_DEFAULT_CONFIG_URL }}' > .env
    
    - name:  Build Project Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run test:unit
    - run: npm run build --if-present
    
    - name:  Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: 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
        publish_dir: ./dist
